### PR TITLE
Docs clean-up

### PR DESCRIPTION
**Pull request by jaredmorgs**
Hi @anthonny 

I've removed all the static docs files *except* for the translations. I'm not sure if the HubPress community would use those when re-translating the GitBook. 

I've updated the README with some of the stuff we've learned running the project over the years. 

⚠️  I have set the README GIF path to the `/docs/images` directory in `/development`. If this path will break when CI runs, we will need to find another way of storing the image so it shows up when the project is forked by our users.

### CODE REVIEW

**Comment by jaredmorgs** [comment]
Make sure you check that GIF path, @anthonny 

I'm fearful that it will break once merged.

**Comment by anthonny** [comment]
I upload the image here to get a cloud URL, we will find a better solution after
what-is-hubpress

**Comment by anthonny** [comment]
shit i did the merge manually yesterday but github do not consider the branch as merged :/

**Comment by jaredmorgs** [comment]
Did I miss pushing some changes into the PR? GitHub, you're drunk. Go home. 😛

**Pull request closed without merging**
